stages:
  - deploy

before_script:
  - apk add rsync openssh curl
  - cp $CI_ENV ${CI_PROJECT_DIR}/.env.production

deploy:
  image: alpine
  stage: deploy
  only:
    - tags
  script:
    - mkdir -p ~/.ssh
    - echo "$CI_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    # -I, --ignore-times don't skip files that match size and time
    - rsync -avI --exclude='.git/' --progress ./ $CI_REMOTE_USERNAME@$CI_REMOTE_HOST:$CI_REMOTE_PATH
    - ssh $CI_REMOTE_USERNAME@$CI_REMOTE_HOST "CI_ELASTIC_PASSWORD=$CI_ELASTIC_PASSWORD CI_POSTGRES_PASSWORD=$CI_POSTGRES_PASSWORD cd $CI_REMOTE_PATH && sudo docker-compose up -d --build"
    - curl -s -X POST "https://api.telegram.org/bot$CI_TG_BOT_TOKEN/sendMessage" -d chat_id=$CI_TG_BOT_CHAT_ID -d text="monsts $CI_COMMIT_TAG deploy finished."
